<a href="https://colab.research.google.com/github/Asit-1121130118/practice-projects/blob/master/cotton%20disease%20prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Cotton disease prediction**

*Making the prediction for diseased cotton leaf using CNN model*

***Importing the required library***

In [1]:
# importing the libraries

import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# checking the version for tensorflow
print(tf.__version__)

2.3.0


*using ImageDataGenerator for preprocessing the image and scaling it.*

In [2]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Part 1 - Data Preprocessing

# Preprocessing the Training set
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)


In [3]:
training_set = train_datagen.flow_from_directory('/content/drive/MyDrive/datasets/Cotton Disease/train',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')


Found 715 images belonging to 2 classes.


In [4]:
# Preprocessing the Test set
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('/content/drive/MyDrive/datasets/Cotton Disease/test',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

Found 51 images belonging to 2 classes.


***Building the Model***

In [5]:
from tensorflow.keras.layers import Conv2D

# Part 2 - Building the CNN

# Initialising the CNN
cnn = tf.keras.models.Sequential()

# Step 1 - Convolution
cnn.add(tf.keras.layers.Conv2D(filters=32,padding="same",kernel_size=3, activation='relu', input_shape=[64, 64, 3]))

# Step 2 - Pooling
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Adding a second convolutional layer
cnn.add(tf.keras.layers.Conv2D(filters=32,padding='same',kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Step 3 - Flattening
cnn.add(tf.keras.layers.Flatten())

# Step 4 - Full Connection
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# Step 5 - Output Layer
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [6]:
cnn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 64, 64, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 8192)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               1048704   
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 1

In [7]:
# Part 3 - Training the CNN

# Compiling the CNN
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the CNN on the Training set and evaluating it on the Test set
cnn.fit(x = training_set, validation_data = test_set, epochs = 20)

Epoch 1/20
23/23 [==============================] - 14s 596ms/step - loss: 0.6827 - accuracy: 0.5846 - val_loss: 0.5539 - val_accuracy: 0.7255
Epoch 2/20
23/23 [==============================] - 12s 531ms/step - loss: 0.4290 - accuracy: 0.8308 - val_loss: 0.2997 - val_accuracy: 0.8824
Epoch 3/20
23/23 [==============================] - 12s 527ms/step - loss: 0.3351 - accuracy: 0.8531 - val_loss: 0.2993 - val_accuracy: 0.8431
Epoch 4/20
23/23 [==============================] - 12s 524ms/step - loss: 0.2703 - accuracy: 0.8951 - val_loss: 0.3350 - val_accuracy: 0.8235
Epoch 5/20
23/23 [==============================] - 12s 527ms/step - loss: 0.2876 - accuracy: 0.8755 - val_loss: 0.2920 - val_accuracy: 0.8235
Epoch 6/20
23/23 [==============================] - 12s 529ms/step - loss: 0.2513 - accuracy: 0.8895 - val_loss: 0.2302 - val_accuracy: 0.9020
Epoch 7/20
23/23 [==============================] - 12s 525ms/step - loss: 0.2418 - accuracy: 0.8923 - val_loss: 0.2161 - val_accuracy: 0.8824

In [8]:
# save it as a h5 file


from tensorflow.keras.models import load_model

cnn.save('model_cotton_disease.h5')

In [9]:
from tensorflow.keras.models import load_model
 
# load model
model = load_model('model_cotton_disease.h5')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 64, 64, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 8192)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               1048704   
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 1

In [11]:
# Part 4 - Making a single prediction from test data
# image taken from test deseased cotton leaf

import numpy as np
from tensorflow.keras.preprocessing import image
test_image = image.load_img('/content/drive/MyDrive/datasets/Cotton Disease/test/diseased cotton leaf/dis_leaf (277)_iaip.jpg', target_size = (64,64))
test_image = image.img_to_array(test_image)
test_image=test_image/255
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)

In [12]:
result

array([[0.16747648]], dtype=float32)

In [13]:
# making prediction for image taken from test fresh cooton leaf

import numpy as np
from tensorflow.keras.preprocessing import image
test_image = image.load_img('/content/drive/MyDrive/datasets/Cotton Disease/test/fresh cotton leaf/d (63)_iaip.jpg', target_size = (64,64))
test_image = image.img_to_array(test_image)
test_image=test_image/255
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
result

array([[0.95931304]], dtype=float32)

In [14]:
# image taken from validation set

import numpy as np
from tensorflow.keras.preprocessing import image
test_image = image.load_img('/content/drive/MyDrive/datasets/Cotton Disease/val/fresh cotton leaf/d (143)_iaip.jpg', target_size = (64,64))
test_image = image.img_to_array(test_image)
test_image=test_image/255
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)

In [15]:
result

array([[0.9991223]], dtype=float32)

In [16]:
if result[0]<=0.5:
    print("The image classified is diseased cotton")
else:
    print("The image classified is fresh cotton")

The image classified is fresh cotton
